version: '2'
# define all services
services:
  # our service is called user_mservice ;-)
  user_service:
    # we want to use the image which is build from our Dockerfile
    build: .
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    ports:
      - "8081:80"
    # we depending on the mysql backend
    depends_on:
      - mysql
  mysql:
    # we use the mysql base image, version 5.6.36
    image: mysql:5.6.36
    ports:
      - 3306:3306
    # we mount a datavolume to make sure we don't loose data
    volumes:
      - db_data:/var/lib/mysql
    # setting some envvars to create the DB
    environment:
      - MYSQL_DATABASE=erp_user
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
volumes:
    db_data: